item {
  name: "bend/bow (at the waist)"
  id: 1
}
item {
  name: "crouch/kneel"
  id: 3
}
item {
  name: "dance"
  id: 4
}
item {
  name: "fall down"
  id: 5
}
item {
  name: "get up"
  id: 6
}
item {
  name: "jump/leap"
  id: 7
}
item {
  name: "lie/sleep"
  id: 8
}
item {
  name: "martial art"
  id: 9
}
item {
  name: "run/jog"
  id: 10
}
item {
  name: "sit"
  id: 11
}
item {
  name: "stand"
  id: 12
}
item {
  name: "swim"
  id: 13
}
item {
  name: "walk"
  id: 14
}